#!/usr/bin/env node
require('shelljs/global');
var program = require('commander');
var path = require('path');

program
    .parse(process.argv);

var appFile = path.join(process.cwd(), process.argv[2] || 'all');
console.log('appFile', appFile);
exec('pm2 stop ' + appFile);

