#!/usr/bin/env node
require('shelljs/global');
var program = require('commander');
var path = require('path');

program
  .parse(process.argv);

var appFile = process.argv[2] || 'all';

exec(`${__dirname}/../node_modules/.bin/pm2 stop ${appFile}`);

