#!/usr/bin/env node
require('shelljs/global');
var program = require('commander');
var path = require('path');

program
    .parse(process.argv);

var appFile = process.argv[2] || 'all';
exec('pm2 delete ' + appFile);
