#!/usr/bin/env node
require('shelljs/global');
var path = require('path');
var program = require('commander');

program.parse(process.argv);


var appFile = program.args[0];
var configFile = path.join(process.cwd(), program.args[1]);


process.env.PARKA_CONFIG_FILE = configFile;
exec(`${__dirname}/../node_modules/.bin/nodemon -e ts -x ${__dirname}/../node_modules/.bin/ts-node ${appFile}`);

process.exit(0);
