#!/usr/bin/env node
require('shelljs/global');
var path = require('path');
var program = require('commander');


program
    .option('-d, --daemon', 'run the app as a background process')
    .option('-i, --instances <number>', 'the number of instances in the cluster, defaults to max')
    .parse(process.argv);

var appFile = path.join(process.cwd(), process.argv[2]);
var configFile = path.join(process.cwd(), process.argv[3]);

var instances = program.instances || 0;

if (program.daemon) {
    exec('export PARKA_CONFIG_FILE='+ configFile +' && pm2 start '+ appFile +' --name '+ appFile +' -i '+ instances +'  --node-args="--require ts-node/register" -l ./logs/full.log -o ./logs/out.log -e ./logs/err.log');

} else {

    exec('export PARKA_CONFIG_FILE='+ configFile +' && pm2 start '+ appFile +' --name '+ appFile +' --no-daemon --watch  --node-args="--require ts-node/register" -l ./logs/full.log -o ./logs/out.log -e ./logs/err.log');

}


process.exit(0);
